name: cheff
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.20
  - pillow=10.4.0
  - pip:
      - torch==2.0.1
      - torchvision==0.15.2
      - fastai==2.7.12
      - matplotlib==3.9.2
